### ISSUE TITLE
Crashes when visiting reddit links (internally opening x-posts behaviour) 

### ISSUE THREAD

**Issue by obosob** [michael-lazar/rtv#173]
When you follow a reddit comments link (x-post) rtv exits with "Forbidden: HTTP Error"

**Comment by zambonin** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.5', 'console_scripts', 'rtv')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/__main__.py", line 138, in <module>
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/__main__.py", line 118, in main
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/subreddit.py", line 50, in loop
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/page.py", line 225, in trigger
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/subreddit.py", line 122, in open_link
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/submission.py", line 28, in __init__
  File "/usr/lib/python3.5/site-packages/rtv-1.5-py3.5.egg/rtv/content.py", line 195, in from_url
  File "/usr/lib/python3.5/site-packages/praw/__init__.py", line 1043, in get_submission
    params=params)
  File "<decorator-gen-191>", line 2, in from_url
  File "/usr/lib/python3.5/site-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/praw/objects.py", line 1111, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/lib/python3.5/site-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/praw/__init__.py", line 612, in request_json
    retry_on_error=retry_on_error)
  File "/usr/lib/python3.5/site-packages/praw/__init__.py", line 445, in _request
    _raise_response_exceptions(response)
  File "/usr/lib/python3.5/site-packages/praw/internal.py", line 205, in _raise_response_exceptions
    raise Forbidden(_raw=response)
praw.errors.Forbidden: HTTP error
```

this is the full traceback from rtv 1.5, when this exact feature was introduced. it persists until 1.6.1.

the good news is that the branch `future-work` fixes this, somewhere among that healthy pile of commits. :)

@michael-lazar if you could remove the `[3:]` slice from [this](https://github.com/michael-lazar/rtv/blob/future_work/rtv/content.py#L150) line, it would fix an aesthetic regression and eliminate the issue completely.

**Comment by michael-lazar** [comment]
Done, thanks for looking into it!

**Comment by obosob** [comment]
This didn't actually fix the bug, just regressed the behaviour. crossposts now act like selfposts, [ENTER] or [o] open the comments of the post like [l]/[RIGHT].

**Comment by zambonin** [comment]
sorry for not looking into this earlier, i wasn't home. however, here's what i found out:

seems like the problem is caused by `open_submission` on `subreddit.py`:

```
if url is None:
    data = self.content.get(self.nav.absolute_index)
    url = data['permalink']
```

where the url, in the case of a x-post, shouldn't be the permalink, instead being the url_full value. if we just replace that, though, rtv can't access x-posts, warning about this HTTP error. the only thing that differs from the two links i tested (generally, when dealing with x-posts and selfposts, i use /r/bestof as a test bench) was the `np` prefix on the URL. 

the issue could be fixed with a dirty hack but that mustn't be the best solution, and most definitely not the only one: `url = data['url_full'].replace('np.', 'www.')`

**Comment by michael-lazar** [comment]
Ok let's try this again, here's the behavior after the latest patch:

![screenshot from 2015-12-03 23 32 31](https://cloud.githubusercontent.com/assets/5026795/11584151/42bce498-9a16-11e5-9461-97b54adeca0a.png)

<kbd>l</kbd> / <kbd>right</kbd>: Opens the x-post, E.g. ``https://www.reddit.com/r/bestof/comments/3vau12/redditor_explains_russian_jokes_with_humorous/``. Does not mark the link as purple.

<kbd>Enter</kbd> / <kbd>o</kbd> Opens the original post, E.g. ``https://www.reddit.com/r/pics/comments/3v7h5c/bought_a_1899_copy_of_tolstoys_resurrection_for_2/cxml7qn?context=3``. Marks the link as purple.

I think this is correct now, please let me know if I missed something.

**Comment by obosob** [comment]
just done some more poking on this as i am still getting the Forbidden HTTP error (no crash though). It appears only to happen when logged in since OAUTH was introduced. I assume there is something in the OAUTH API that an app has to make some guarantees or acknowledgement of an np link.
